name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf \
            automake \
            libtool \
            help2man \
            make \
            gcc \
            pkg-config

      - name: Bootstrap
        run: script/bootstrap.sh

      - name: Configure
        run: ./configure

      - name: Build
        run: make

      - name: Generate distribution
        run: make dist
        env:
          CI: true

      - name: Obtain release body
        run: |
          ./script/get_changelog.sh "${GITHUB_REF_NAME}" > body.md

      - name: Find artifact
        run: |
          ARTIFACT_PATHNAME="$(ls debugfatfs-*.tar.gz | head -n 1)"
          test -n "${ARTIFACT_PATHNAME}"

          echo "ARTIFACT_PATHNAME=${ARTIFACT_PATHNAME}" >> "$GITHUB_ENV"
          echo "ARTIFACT_NAME=$(basename "${ARTIFACT_PATHNAME}")" >> "$GITHUB_ENV"

      - name: Create release
        run: |
          gh release create "${GITHUB_REF_NAME}" \
            "${ARTIFACT_PATHNAME}" \
            --title "Release ${GITHUB_REF_NAME}" \
            --notes-file body.md \
            --verify-tag
        env:
          GH_TOKEN: ${{ github.token }}